analysis_metrics:
  default:
    - id: new_lines
      source: Sonar
      
    - id: new_coverage
      source: Sonar

    - id: files
      source: Sonar

  radar:
    - id: complexity
      checked: true
      source: Sonar
      thresholds:
        a:
          lower_bound: 0
          upper_bound: 8
        b:
          lower_bound: 8
          upper_bound: 16
        c:
          lower_bound: 16
          upper_bound: 24
        d:
          lower_bound: 24
          upper_bound: 32
        e:
          lower_bound: 32
          upper_bound: 40  # Upper limit is +40

    - id: cognitive_complexity
      checked: true
      source: Sonar
      thresholds:
        a:
          lower_bound: 0
          upper_bound: 12
        b:
          lower_bound: 12
          upper_bound: 25
        c:
          lower_bound: 25
          upper_bound: 35
        d:
          lower_bound: 35
          upper_bound: 45
        e:
          lower_bound: 45
          upper_bound: 50  # Upper limit is +15
      
    - id: instability
      checked: true
      source: CodeQL
      thresholds:
        a:
          lower_bound: 0
          upper_bound: 0.2
        b:
          lower_bound: 0.2
          upper_bound: 0.4
        c:
          lower_bound: 0.4
          upper_bound: 0.6
        d:
          lower_bound: 0.6
          upper_bound: 0.8
        e:
          lower_bound: 0.8
          upper_bound: 1  # Upper limit is 100%

    - id: lackOfCohesion
      checked: true
      source: CodeQL
      thresholds:
        a:
          lower_bound: 0
          upper_bound: 1
        b:
          lower_bound: 1
          upper_bound: 2
        c:
          lower_bound: 2
          upper_bound: 3
        d:
          lower_bound: 3
          upper_bound: 4
        e:
          lower_bound: 4
          upper_bound: 5  # Upper limit is +5

